### ISSUE TITLE
Improve accessibility of icons for screen readers

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Icon-fonts#25]
Where an icon has been used an `aria-label` is not present, we should hide the icon from screen readers.

Proposed code:

```css
@media speech {
  .icon.icon-common:not([aria-label]),
  .icon.icon-socialmedia:not([aria-label]),
  .icon.icon-species:not([aria-label]),
  .icon.icon-generic:not([aria-label]),
  .icon.icon-fileformats:not([aria-label]),
  .icon.icon-functional:not([aria-label]),
  .icon.icon-chemistry:not([aria-label]) {
    display:none;
  }
}
```

Thanks to @esanzgar for spurring this one.
